services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "7540:7540"
    volumes:
      - .:/usr/src/app
    command: go run main.go '$TODO_PORT, $TODO_DBFILE, $TODO_PASSWORD'
  db:
    image: postgres:alpine
    environment:
      - TODO_PORT =${TODO_PORT}
      - TODO_DBFILE =${TODO_DBFILE}
      - TODO_PASSWORD =${TODO_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: